package com.example.util

data class LanguageOption(
    val code: String,
    val name: String,
    val nativeName: String,
    val flag: String
)

object LanguageManager {

    val supportedLanguages = listOf(
        LanguageOption("id", "Bahasa Indonesia", "Indonesia", "🇮🇩"),
        LanguageOption("en", "English", "English", "🇺🇸"),
        LanguageOption("it", "Italiano", "Italia", "🇮🇹"),
        LanguageOption("fr", "Français", "Prancis", "🇫🇷"),
        LanguageOption("ar", "العربية", "Arab", "🇸🇦"),
        LanguageOption("de", "Deutsch", "Jerman", "🇩🇪"),
        LanguageOption("es", "Español", "Spanyol", "🇪🇸"),
        LanguageOption("ja", "日本語", "Jepang", "🇯🇵"),
        LanguageOption("ko", "한국어", "Korea", "🇰🇷"),
        LanguageOption("zh", "中文", "China", "🇨🇳"),
        LanguageOption("pt", "Português", "Portugis", "🇧🇷"),
        LanguageOption("ru", "Русский", "Rusia", "🇷🇺"),
        LanguageOption("tr", "Türkçe", "Turki", "🇹🇷"),
        LanguageOption("nl", "Nederlands", "Belanda", "🇳🇱"),
        LanguageOption("pl", "Polski", "Polandia", "🇵🇱"),
        LanguageOption("hi", "हिन्दी", "India", "🇮🇳"),
        LanguageOption("vi", "Tiếng Việt", "Vietnam", "🇻🇳"),
        LanguageOption("th", "ไทย", "Thailand", "🇹🇭")
    )

    private val translations = mapOf(
        "id" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "Asisten AI Cerdas",
            "onlineRealtime" to "Online & Real-time",
            "fitur" to "Fitur",
            "flashcardTitle" to "Flashcard Zann AI",
            "flashcardSub" to "Kuis & Pembuat Otomatis",
            "memoryTitle" to "Memori Belajar Zann AI",
            "memorySub" to "Basis Pengetahuan Kustom",
            "plannerTitle" to "Rencana Belajar Zann AI",
            "plannerSub" to "Pecah Topik Sesuai Target",
            "paletteTitle" to "Palet Warna Zann AI",
            "paletteSub" to "Tema & Skema Warna App",
            "languageTitle" to "Ganti Bahasa",
            "languageSub" to "Bahasa Tampilan Zann AI",
            "newChat" to "Percakapan Baru",
            "chatHistory" to "RIWAYAT OBROLAN",
            "searchChatPlaceholder" to "Cari obrolan...",
            "noHistory" to "Belum Ada Riwayat",
            "deleteChat" to "Hapus Chat",
            "openMenu" to "Buka Menu",
            "aiLiveMode" to "Zann AI Live",
            "toggleTheme" to "Ganti Tema",
            "typeMessagePlaceholder" to "Ketik pesan Anda ke Zann AI...",
            "tutorPhotoTask" to "Tutor Foto Tugas AI",
            "addFile" to "Tambahkan File",
            "webGrounding" to "Web Grounding",
            "webGroundingOn" to "Pencarian Web Otomatis",
            "webGroundingOff" to "Tanpa Pencarian Web",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "PROMPT REKOMENDASI",
            "welcomeText" to "Asisten AI online cerdas yang dibekali aneka model (Zann-Flash / Zann-Pro) serta upload file dan perekaman voice note real-time.",
            "prompt1Title" to "Beri ide teknologi masa depan",
            "prompt1Sub" to "Inspirasi & ide kreatif",
            "prompt2Title" to "Review ringkas buku fiksi bagus",
            "prompt2Sub" to "Rekomendasi literatur",
            "prompt3Title" to "Tips produktif di pagi hari",
            "prompt3Sub" to "Pengembangan diri",
            "selectThemeTitle" to "Pilih Palet Tema Warna",
            "selectThemeSub" to "Silakan pilih skema warna yang menarik untuk Zann AI & Flashcard:",
            "selectLanguageTitle" to "Ganti Bahasa Zann AI",
            "selectLanguageSub" to "Pilih bahasa tampilan untuk seluruh antarmuka Zann AI:",
            "close" to "Tutup",
            "cancel" to "Batal",
            "save" to "Simpan",
            "active" to "Aktif",
            "voiceRecord" to "Merekam Pesan Suara",
            "systemGrayTheme" to "Sistem (Abu-abu Gelap)",
            "systemGrayDesc" to "Abu-abu Gelap, Minimalis, Netral Sistem"
        ),
        "en" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "Smart AI Assistant",
            "onlineRealtime" to "Online & Real-time",
            "fitur" to "Features",
            "flashcardTitle" to "Zann AI Flashcards",
            "flashcardSub" to "Quizzes & Auto Generator",
            "memoryTitle" to "Zann AI Learning Memory",
            "memorySub" to "Custom Knowledge Base",
            "plannerTitle" to "Zann AI Study Planner",
            "plannerSub" to "Breakdown Topics by Target",
            "paletteTitle" to "Zann AI Color Palette",
            "paletteSub" to "App Theme & Color Scheme",
            "languageTitle" to "Change Language",
            "languageSub" to "Zann AI Display Language",
            "newChat" to "New Conversation",
            "chatHistory" to "CHAT HISTORY",
            "searchChatPlaceholder" to "Search chats...",
            "noHistory" to "No History Yet",
            "deleteChat" to "Delete Chat",
            "openMenu" to "Open Menu",
            "aiLiveMode" to "Zann AI Live",
            "toggleTheme" to "Toggle Theme",
            "typeMessagePlaceholder" to "Type your message to Zann AI...",
            "tutorPhotoTask" to "AI Homework Photo Tutor",
            "addFile" to "Attach File",
            "webGrounding" to "Web Grounding",
            "webGroundingOn" to "Auto Web Search Enabled",
            "webGroundingOff" to "Offline Model Responses",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "RECOMMENDED PROMPTS",
            "welcomeText" to "Smart online AI assistant powered by multiple models (Zann-Flash / Zann-Pro) with file upload and real-time voice notes.",
            "prompt1Title" to "Give future technology ideas",
            "prompt1Sub" to "Inspiration & creative ideas",
            "prompt2Title" to "Short review of a good fiction book",
            "prompt2Sub" to "Literature recommendation",
            "prompt3Title" to "Productive morning routine tips",
            "prompt3Sub" to "Personal growth",
            "selectThemeTitle" to "Select Color Theme",
            "selectThemeSub" to "Choose an attractive color scheme for Zann AI & Flashcards:",
            "selectLanguageTitle" to "Change Zann AI Language",
            "selectLanguageSub" to "Choose display language for the entire Zann AI interface:",
            "close" to "Close",
            "cancel" to "Cancel",
            "save" to "Save",
            "active" to "Active",
            "voiceRecord" to "Recording Voice Note",
            "systemGrayTheme" to "System (Dark Gray)",
            "systemGrayDesc" to "Dark Gray, Minimalist, System Neutral"
        ),
        "ar" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "مساعد الذكاء الاصطناعي الذكي",
            "onlineRealtime" to "متصل ومباشر",
            "fitur" to "الميزات",
            "flashcardTitle" to "بطاقات Zann AI التعليمية",
            "flashcardSub" to "اختبارات ومولد تلقائي",
            "memoryTitle" to "ذاكرة التعلم Zann AI",
            "memorySub" to "قاعدة معرفة مخصصة",
            "plannerTitle" to "مخطط الدراسة Zann AI",
            "plannerSub" to "تقسيم المواضيع حسب الهدف",
            "paletteTitle" to "لوحة الألوان Zann AI",
            "paletteSub" to "ثيم ومظهر التطبيق",
            "languageTitle" to "تغيير اللغة",
            "languageSub" to "لغة واجهة Zann AI",
            "newChat" to "محادثة جديدة",
            "chatHistory" to "سجل المحادثات",
            "searchChatPlaceholder" to "البحث في المحادثات...",
            "noHistory" to "لا يوجد سجل بعد",
            "deleteChat" to "حذف المحادثة",
            "openMenu" to "فتح القائمة",
            "aiLiveMode" to "Zann AI المباشر",
            "toggleTheme" to "تغيير الثيم",
            "typeMessagePlaceholder" to "اكتب رسالتك إلى Zann AI...",
            "tutorPhotoTask" to "معلم صورة الواجب بالذكاء الاصطناعي",
            "addFile" to "إرفاق ملف",
            "webGrounding" to "البحث عبر الإنترنت",
            "webGroundingOn" to "البحث المباشر مفعل",
            "webGroundingOff" to "بدون بحث إنترنت",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "مقترحات المحادثة",
            "welcomeText" to "مساعد ذكاء اصطناعي ذكي عبر الإنترنت يدعم نماذج متعددة (Zann-Flash / Zann-Pro) ورفع الملفات والرسائل الصوتية المباشرة.",
            "prompt1Title" to "أفكار لتكنولوجيا المستقبل",
            "prompt1Sub" to "إلهام وأفكار إبداعية",
            "prompt2Title" to "مراجعة كتاب خيالي مميز",
            "prompt2Sub" to "ترشيحات كتب",
            "prompt3Title" to "نصائح لصباح أكثر إنتاجية",
            "prompt3Sub" to "تطوير الذات",
            "selectThemeTitle" to "اختر ثيم الألوان",
            "selectThemeSub" to "اختر نمط الألوان المفضل لديك لـ Zann AI والبطاقات:",
            "selectLanguageTitle" to "تغيير لغة Zann AI",
            "selectLanguageSub" to "اختر اللغة المناسبة لواجهة التطبيق الكاملة:",
            "close" to "إغلاق",
            "cancel" to "إلغاء",
            "save" to "حفظ",
            "active" to "نشط",
            "voiceRecord" to "تسجيل صوتي",
            "systemGrayTheme" to "النظام (رمادي داكن)",
            "systemGrayDesc" to "رمادي داكن محايد وبسيط"
        ),
        "it" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "Assistente IA Intelligente",
            "onlineRealtime" to "Online & In Tempo Reale",
            "fitur" to "Funzioni",
            "flashcardTitle" to "Flashcard Zann AI",
            "flashcardSub" to "Quiz e Generatore Automatico",
            "memoryTitle" to "Memoria di Apprendimento Zann AI",
            "memorySub" to "Base di Conoscenza Personalizzata",
            "plannerTitle" to "Pianificatore di Studio Zann AI",
            "plannerSub" to "Suddividi Argomenti per Obiettivo",
            "paletteTitle" to "Tavolozza Colori Zann AI",
            "paletteSub" to "Tema e Schema Colori",
            "languageTitle" to "Cambia Lingua",
            "languageSub" to "Lingua dell'Interfaccia Zann AI",
            "newChat" to "Nuova Conversazione",
            "chatHistory" to "CRONOLOGIA CHAT",
            "searchChatPlaceholder" to "Cerca chat...",
            "noHistory" to "Nessuna Cronologia",
            "deleteChat" to "Elimina Chat",
            "openMenu" to "Apri Menu",
            "aiLiveMode" to "Zann AI Live",
            "toggleTheme" to "Cambia Tema",
            "typeMessagePlaceholder" to "Scrivi il tuo messaggio a Zann AI...",
            "tutorPhotoTask" to "Tutor Foto Compiti IA",
            "addFile" to "Allega File",
            "webGrounding" to "Ricerca Web",
            "webGroundingOn" to "Ricerca Web Automatica",
            "webGroundingOff" to "Senza Ricerca Web",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "PROMPT CONSIGLIATI",
            "welcomeText" to "Assistente IA intelligente online con modelli avanzati (Zann-Flash / Zann-Pro), invio file e note vocali in tempo reale.",
            "prompt1Title" to "Idee tecnologiche del futuro",
            "prompt1Sub" to "Ispirazione e creatività",
            "prompt2Title" to "Recensione di un bel libro",
            "prompt2Sub" to "Consiglio di lettura",
            "prompt3Title" to "Consigli per una mattina produttiva",
            "prompt3Sub" to "Crescita personale",
            "selectThemeTitle" to "Seleziona Tema Colore",
            "selectThemeSub" to "Scegli uno schema di colori per Zann AI:",
            "selectLanguageTitle" to "Cambia Lingua Zann AI",
            "selectLanguageSub" to "Scegli la lingua per l'intera interfaccia:",
            "close" to "Chiudi",
            "cancel" to "Annulla",
            "save" to "Salva",
            "active" to "Attivo",
            "voiceRecord" to "Registrazione Vocale",
            "systemGrayTheme" to "Sistema (Grigio Scuro)",
            "systemGrayDesc" to "Grigio Scuro, Minimalista"
        ),
        "fr" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "Assistant IA Intelligent",
            "onlineRealtime" to "En Ligne & Temps Réel",
            "fitur" to "Fonctionnalités",
            "flashcardTitle" to "Cartes Flash Zann AI",
            "flashcardSub" to "Quiz & Générateur Auto",
            "memoryTitle" to "Mémoire d'Apprentissage Zann AI",
            "memorySub" to "Base de Connaissances Personalissée",
            "plannerTitle" to "Planificateur d'Études Zann AI",
            "plannerSub" to "Organiser par Objectif",
            "paletteTitle" to "Palette de Couleurs Zann AI",
            "paletteSub" to "Thème & Couleurs",
            "languageTitle" to "Changer de Langue",
            "languageSub" to "Langue d'Affichage Zann AI",
            "newChat" to "Nouvelle Conversation",
            "chatHistory" to "HISTORIQUE DU CHAT",
            "searchChatPlaceholder" to "Rechercher...",
            "noHistory" to "Aucun Historique",
            "deleteChat" to "Supprimer le Chat",
            "openMenu" to "Ouvrir le Menu",
            "aiLiveMode" to "Zann AI Live",
            "toggleTheme" to "Changer de Thème",
            "typeMessagePlaceholder" to "Écrivez à Zann AI...",
            "tutorPhotoTask" to "Tuteur Photo Devoirs IA",
            "addFile" to "Joindre un Fichier",
            "webGrounding" to "Recherche Web",
            "webGroundingOn" to "Recherche Web Activée",
            "webGroundingOff" to "Mode Hors Ligne",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "SUGGESTIONS DE PROMPT",
            "welcomeText" to "Assistant IA intelligent en ligne avec prise en charge des fichiers et notes vocales en temps réel.",
            "prompt1Title" to "Idées de technologies futures",
            "prompt1Sub" to "Inspiration créative",
            "prompt2Title" to "Critique d'un bon livre",
            "prompt2Sub" to "Recommandation lecture",
            "prompt3Title" to "Conseils routine du matin",
            "prompt3Sub" to "Développement personnel",
            "selectThemeTitle" to "Thème de Couleurs",
            "selectThemeSub" to "Choisissez un thème pour l'application :",
            "selectLanguageTitle" to "Changer la Langue",
            "selectLanguageSub" to "Sélectionnez la langue de l'application :",
            "close" to "Fermer",
            "cancel" to "Annuler",
            "save" to "Enregistrer",
            "active" to "Actif",
            "voiceRecord" to "Enregistrement Vocal",
            "systemGrayTheme" to "Système (Gris Foncé)",
            "systemGrayDesc" to "Gris Foncé, Minimaliste"
        ),
        "de" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "Intelligenter KI-Assistent",
            "onlineRealtime" to "Online & Echtzeit",
            "fitur" to "Funktionen",
            "flashcardTitle" to "Zann AI Karteikarten",
            "flashcardSub" to "Quiz & Auto-Generator",
            "memoryTitle" to "Zann AI Lernspeicher",
            "memorySub" to "Eigene Wissensdatenbank",
            "plannerTitle" to "Zann AI Studienplaner",
            "plannerSub" to "Themen nach Ziel aufteilen",
            "paletteTitle" to "Zann AI Farbpalette",
            "paletteSub" to "App-Design & Farben",
            "languageTitle" to "Sprache Ändern",
            "languageSub" to "Zann AI Anzeigesprache",
            "newChat" to "Neuer Chat",
            "chatHistory" to "CHAT-VERLAUF",
            "searchChatPlaceholder" to "Chats durchsuchen...",
            "noHistory" to "Noch kein Verlauf",
            "deleteChat" to "Chat Löschen",
            "openMenu" to "Menü Öffnen",
            "aiLiveMode" to "Zann AI Live",
            "toggleTheme" to "Design Wechseln",
            "typeMessagePlaceholder" to "Schreibe an Zann AI...",
            "tutorPhotoTask" to "Hausaufgaben-Foto-Tutor",
            "addFile" to "Datei Anheften",
            "webGrounding" to "Web-Suche",
            "webGroundingOn" to "Automatische Web-Suche",
            "webGroundingOff" to "Ohne Web-Suche",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "EMPFOHLENE PROMPTS",
            "welcomeText" to "Intelligenter KI-Assistent mit Dateiupload und Echtzeit-Sprachnachrichten.",
            "prompt1Title" to "Ideen für Zukunftstechnologien",
            "prompt1Sub" to "Inspiration & Kreativität",
            "prompt2Title" to "Kurzkritik eines guten Buches",
            "prompt2Sub" to "Literaturempfehlung",
            "prompt3Title" to "Produktive Morgenroutine-Tipps",
            "prompt3Sub" to "Persönlichkeitsentwicklung",
            "selectThemeTitle" to "Farbschema Wählen",
            "selectThemeSub" to "Wähle ein Farbschema für Zann AI:",
            "selectLanguageTitle" to "Sprache Ändern",
            "selectLanguageSub" to "Wähle die Sprache für die App-Oberfläche:",
            "close" to "Schließen",
            "cancel" to "Abbrechen",
            "save" to "Speichern",
            "active" to "Aktiv",
            "voiceRecord" to "Sprachaufnahme",
            "systemGrayTheme" to "System (Dunkelgrau)",
            "systemGrayDesc" to "Dunkelgrau, Minimalistisch"
        ),
        "es" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "Asistente de IA Inteligente",
            "onlineRealtime" to "En Línea y Tiempo Real",
            "fitur" to "Funciones",
            "flashcardTitle" to "Tarjetas Zann AI",
            "flashcardSub" to "Cuestionarios y Generador",
            "memoryTitle" to "Memoria de Aprendizaje Zann AI",
            "memorySub" to "Base de Conocimiento",
            "plannerTitle" to "Planificador Zann AI",
            "plannerSub" to "Desglosar Temas por Objetivo",
            "paletteTitle" to "Paleta de Colores Zann AI",
            "paletteSub" to "Tema y Colores de App",
            "languageTitle" to "Cambiar Idioma",
            "languageSub" to "Idioma de la Interfaz Zann AI",
            "newChat" to "Nueva Conversación",
            "chatHistory" to "HISTORIAL DE CHAT",
            "searchChatPlaceholder" to "Buscar chats...",
            "noHistory" to "Sin Historial Aún",
            "deleteChat" to "Eliminar Chat",
            "openMenu" to "Abrir Menú",
            "aiLiveMode" to "Zann AI En Vivo",
            "toggleTheme" to "Cambiar Tema",
            "typeMessagePlaceholder" to "Escribe tu mensaje a Zann AI...",
            "tutorPhotoTask" to "Tutor de Fotos de Tareas",
            "addFile" to "Adjuntar Archivo",
            "webGrounding" to "Búsqueda Web",
            "webGroundingOn" to "Búsqueda Web Activada",
            "webGroundingOff" to "Sin Búsqueda Web",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "PROMPTS RECOMENDADOS",
            "welcomeText" to "Asistente inteligente de IA en línea con soporte para archivos y notas de voz en tiempo real.",
            "prompt1Title" to "Ideas de tecnología del futuro",
            "prompt1Sub" to "Inspiración e ideas creativas",
            "prompt2Title" to "Reseña corta de un buen libro",
            "prompt2Sub" to "Recomendación literaria",
            "prompt3Title" to "Consejos para mañanas productivas",
            "prompt3Sub" to "Crecimiento personal",
            "selectThemeTitle" to "Seleccionar Tema de Color",
            "selectThemeSub" to "Elige un esquema de color atractivo:",
            "selectLanguageTitle" to "Cambiar Idioma de Zann AI",
            "selectLanguageSub" to "Selecciona el idioma de la aplicación:",
            "close" to "Cerrar",
            "cancel" to "Cancelar",
            "save" to "Guardar",
            "active" to "Activo",
            "voiceRecord" to "Grabando Nota de Voz",
            "systemGrayTheme" to "Sistema (Gris Oscuro)",
            "systemGrayDesc" to "Gris Oscuro, Minimalista"
        ),
        "ja" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "スマートAIアシスタント",
            "onlineRealtime" to "オンライン & リアルタイム",
            "fitur" to "機能一覧",
            "flashcardTitle" to "Zann AI フラッシュカード",
            "flashcardSub" to "クイズ & 自動生成",
            "memoryTitle" to "Zann AI 学習メモリー",
            "memorySub" to "カスタムナレッジベース",
            "plannerTitle" to "Zann AI 学習プランナー",
            "plannerSub" to "目標別にトピック分解",
            "paletteTitle" to "Zann AI カラーパレット",
            "paletteSub" to "テーマ & カラー",
            "languageTitle" to "言語変更",
            "languageSub" to "表示言語の設定",
            "newChat" to "新しいチャット",
            "chatHistory" to "チャット履歴",
            "searchChatPlaceholder" to "チャットを検索...",
            "noHistory" to "履歴はありません",
            "deleteChat" to "チャット削除",
            "openMenu" to "メニューを開く",
            "aiLiveMode" to "Zann AI ライブ",
            "toggleTheme" to "テーマ切替",
            "typeMessagePlaceholder" to "Zann AIにメッセージを入力...",
            "tutorPhotoTask" to "AI宿題写真チューター",
            "addFile" to "ファイルを添付",
            "webGrounding" to "Webグラウンディング",
            "webGroundingOn" to "Web自動検索ON",
            "webGroundingOff" to "オフライン回答のみ",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "おすすめプロンプト",
            "welcomeText" to "リアルタイム音声録音やファイル分析に対応したスマートAIアシスタント。",
            "prompt1Title" to "未来のテクノロジーのアイデア",
            "prompt1Sub" to "ひらめきとアイデア",
            "prompt2Title" to "面白い小説の要約レビュー",
            "prompt2Sub" to "おすすめの文学",
            "prompt3Title" to "生産的な朝のルーティンのコツ",
            "prompt3Sub" to "自己啓発・成長",
            "selectThemeTitle" to "カラーテーマ選択",
            "selectThemeSub" to "お好みのカラーパレットを選択してください:",
            "selectLanguageTitle" to "言語を選択",
            "selectLanguageSub" to "アプリ全体の表示言語を変更します:",
            "close" to "閉じる",
            "cancel" to "キャンセル",
            "save" to "保存",
            "active" to "アクティブ",
            "voiceRecord" to "音声録音中",
            "systemGrayTheme" to "システム (ダークグレー)",
            "systemGrayDesc" to "ダークグレー, ミニマル"
        ),
        "ko" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "스마트 AI 어시스턴트",
            "onlineRealtime" to "온라인 & 실시간",
            "fitur" to "기능",
            "flashcardTitle" to "Zann AI 플래시카드",
            "flashcardSub" to "퀴즈 및 자동 생성",
            "memoryTitle" to "Zann AI 학습 메모리",
            "memorySub" to "맞춤형 지식 베이스",
            "plannerTitle" to "Zann AI 학습 플래너",
            "plannerSub" to "목표별 주제 세분화",
            "paletteTitle" to "Zann AI 컬러 팔레트",
            "paletteSub" to "앱 테마 및 색상",
            "languageTitle" to "언어 변경",
            "languageSub" to "화면 표시 언어",
            "newChat" to "새 대화",
            "chatHistory" to "대화 기록",
            "searchChatPlaceholder" to "대화 검색...",
            "noHistory" to "대화 기록 없음",
            "deleteChat" to "대화 삭제",
            "openMenu" to "메뉴 열기",
            "aiLiveMode" to "Zann AI 라이브",
            "toggleTheme" to "테마 전환",
            "typeMessagePlaceholder" to "Zann AI에 메시지 입력...",
            "tutorPhotoTask" to "AI 과제 사진 튜터",
            "addFile" to "파일 첨부",
            "webGrounding" to "웹 검색",
            "webGroundingOn" to "실시간 웹 검색 활성화",
            "webGroundingOff" to "오프라인 모델 응답",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "추천 프롬프트",
            "welcomeText" to "파일 업로드 및 실시간 음성 녹음을 지원하는 스마트 온라인 AI 어시스턴트.",
            "prompt1Title" to "미래 기술 아이디어 제공",
            "prompt1Sub" to "영감 및 창의적 아이디어",
            "prompt2Title" to "좋은 소설 책 요약 리뷰",
            "prompt2Sub" to "문학 추천",
            "prompt3Title" to "생산적인 아침 루틴 팁",
            "prompt3Sub" to "자기 계발",
            "selectThemeTitle" to "컬러 테마 선택",
            "selectThemeSub" to "원하는 색상 조합을 선택하세요:",
            "selectLanguageTitle" to "언어 변경",
            "selectLanguageSub" to "앱 전체에 적용할 언어를 선택하세요:",
            "close" to "닫기",
            "cancel" to "취소",
            "save" to "저장",
            "active" to "활성",
            "voiceRecord" to "음성 녹음 중",
            "systemGrayTheme" to "시스템 (다크 그레이)",
            "systemGrayDesc" to "다크 그레이, 미니멀"
        ),
        "zh" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "智能AI助手",
            "onlineRealtime" to "在线 & 实时",
            "fitur" to "功能菜单",
            "flashcardTitle" to "Zann AI 抽认卡",
            "flashcardSub" to "测验与自动生成",
            "memoryTitle" to "Zann AI 学习记忆库",
            "memorySub" to "自定义知识库",
            "plannerTitle" to "Zann AI 学习计划",
            "plannerSub" to "按目标拆解主题",
            "paletteTitle" to "Zann AI 色彩调色板",
            "paletteSub" to "应用主题与配色",
            "languageTitle" to "切换语言",
            "languageSub" to "界面语言设置",
            "newChat" to "新建对话",
            "chatHistory" to "历史对话",
            "searchChatPlaceholder" to "搜索对话...",
            "noHistory" to "暂无历史记录",
            "deleteChat" to "删除对话",
            "openMenu" to "打开菜单",
            "aiLiveMode" to "Zann AI 实时语音",
            "toggleTheme" to "切换主题",
            "typeMessagePlaceholder" to "给 Zann AI 发送消息...",
            "tutorPhotoTask" to "AI 作业拍照辅导",
            "addFile" to "添加文件",
            "webGrounding" to "联网搜索",
            "webGroundingOn" to "自动联网搜索已开启",
            "webGroundingOff" to "仅使用离线模型",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "推荐提示词",
            "welcomeText" to "智能在线 AI 助手，支持多模型（Zann-Flash / Zann-Pro）、文件上传和实时语音录制。",
            "prompt1Title" to "提供未来科技创意",
            "prompt1Sub" to "灵感与创意构想",
            "prompt2Title" to "优秀小说简短书评",
            "prompt2Sub" to "文学作品推荐",
            "prompt3Title" to "高效晨间习惯建议",
            "prompt3Sub" to "个人成长",
            "selectThemeTitle" to "选择主题配色",
            "selectThemeSub" to "请选择您喜欢的主题配色方案：",
            "selectLanguageTitle" to "切换应用语言",
            "selectLanguageSub" to "请选择界面语言：",
            "close" to "关闭",
            "cancel" to "取消",
            "save" to "保存",
            "active" to "当前",
            "voiceRecord" to "正在录音",
            "systemGrayTheme" to "系统 (深灰)",
            "systemGrayDesc" to "深灰色，极简风格"
        ),
        "pt" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "Assistente IA Inteligente",
            "onlineRealtime" to "Online e Tempo Real",
            "fitur" to "Recursos",
            "flashcardTitle" to "Flashcards Zann AI",
            "flashcardSub" to "Quizzes e Gerador Automático",
            "memoryTitle" to "Memória de Aprendizagem",
            "memorySub" to "Base de Conhecimento",
            "plannerTitle" to "Planejador de Estudos",
            "plannerSub" to "Dividir Tópicos por Meta",
            "paletteTitle" to "Paleta de Cores",
            "paletteSub" to "Tema do App",
            "languageTitle" to "Mudar Idioma",
            "languageSub" to "Idioma do Zann AI",
            "newChat" to "Nova Conversa",
            "chatHistory" to "HISTÓRICO DE CHAT",
            "searchChatPlaceholder" to "Buscar conversas...",
            "noHistory" to "Sem Histórico",
            "deleteChat" to "Excluir Chat",
            "openMenu" to "Abrir Menu",
            "aiLiveMode" to "Zann AI Ao Vivo",
            "toggleTheme" to "Mudar Tema",
            "typeMessagePlaceholder" to "Digite sua mensagem para Zann AI...",
            "tutorPhotoTask" to "Tutor de Foto de Tarefas IA",
            "addFile" to "Anexar Arquivo",
            "webGrounding" to "Pesquisa Web",
            "webGroundingOn" to "Pesquisa Web Ativada",
            "webGroundingOff" to "Sem Pesquisa Web",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "SUGESTÕES DE PROMPTS",
            "welcomeText" to "Assistente inteligente de IA online com suporte a múltiplos modelos e gravação de voz.",
            "prompt1Title" to "Ideias de tecnologia do futuro",
            "prompt1Sub" to "Inspiração e ideias criativas",
            "prompt2Title" to "Resenha curta de um bom livro",
            "prompt2Sub" to "Recomendação literária",
            "prompt3Title" to "Dicas para manhãs produtivas",
            "prompt3Sub" to "Desenvolvimento pessoal",
            "selectThemeTitle" to "Tema de Cores",
            "selectThemeSub" to "Escolha o esquema de cores para o aplicativo:",
            "selectLanguageTitle" to "Mudar Idioma",
            "selectLanguageSub" to "Selecione o idioma de exibição do aplicativo:",
            "close" to "Fechar",
            "cancel" to "Cancelar",
            "save" to "Salvar",
            "active" to "Ativo",
            "voiceRecord" to "Gravando Nota de Voz",
            "systemGrayTheme" to "Sistema (Cinza Escuro)",
            "systemGrayDesc" to "Cinza Escuro, Minimalista"
        ),
        "ru" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "Умный ИИ-ассистент",
            "onlineRealtime" to "Онлайн и в реальном времени",
            "fitur" to "Функции",
            "flashcardTitle" to "Флеш-карточки Zann AI",
            "flashcardSub" to "Тесты и автогенерация",
            "memoryTitle" to "Память обучения Zann AI",
            "memorySub" to "База знаний",
            "plannerTitle" to "План учебы Zann AI",
            "plannerSub" to "Разбивка тем по целям",
            "paletteTitle" to "Цветовая палитра Zann AI",
            "paletteSub" to "Тема приложения",
            "languageTitle" to "Сменить язык",
            "languageSub" to "Язык интерфейса Zann AI",
            "newChat" to "Новый чат",
            "chatHistory" to "ИСТОРИЯ ЧАТОВ",
            "searchChatPlaceholder" to "Поиск чатов...",
            "noHistory" to "Истории пока нет",
            "deleteChat" to "Удалить чат",
            "openMenu" to "Открыть меню",
            "aiLiveMode" to "Zann AI Live",
            "toggleTheme" to "Сменить тему",
            "typeMessagePlaceholder" to "Напишите сообщение Zann AI...",
            "tutorPhotoTask" to "ИИ-репетитор по фото",
            "addFile" to "Прикрепить файл",
            "webGrounding" to "Веб-поиск",
            "webGroundingOn" to "Авто-поиск в веб включен",
            "webGroundingOff" to "Без веб-поиска",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "РЕКОМЕНДУЕМЫЕ ПРОМПТЫ",
            "welcomeText" to "Умный ИИ-ассистент с поддержкой файлов и голосовых сообщений в реальном времени.",
            "prompt1Title" to "Идеи технологий будущего",
            "prompt1Sub" to "Вдохновение и идеи",
            "prompt2Title" to "Краткий обзор хорошей книги",
            "prompt2Sub" to "Рекомендация литературы",
            "prompt3Title" to "Советы для продуктивного утра",
            "prompt3Sub" to "Личностный рост",
            "selectThemeTitle" to "Выбор темы",
            "selectThemeSub" to "Выберите цветовую схему для Zann AI:",
            "selectLanguageTitle" to "Сменить язык Zann AI",
            "selectLanguageSub" to "Выберите язык интерфейса приложения:",
            "close" to "Закрыть",
            "cancel" to "Отмена",
            "save" to "Сохранить",
            "active" to "Активно",
            "voiceRecord" to "Запись голосового сообщения",
            "systemGrayTheme" to "Системная (Темно-серая)",
            "systemGrayDesc" to "Темно-серый минимализм"
        ),
        "tr" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "Akıllı Yapay Zeka Asistanı",
            "onlineRealtime" to "Çevrimiçi ve Eşzamanlı",
            "fitur" to "Özellikler",
            "flashcardTitle" to "Zann AI Bilgi Kartları",
            "flashcardSub" to "Testler ve Otomatik Oluşturucu",
            "memoryTitle" to "Zann AI Öğrenme Hafızası",
            "memorySub" to "Özel Bilgi Tabanı",
            "plannerTitle" to "Zann AI Çalışma Planlayıcı",
            "plannerSub" to "Konuları Hedefe Göre Böl",
            "paletteTitle" to "Zann AI Renk Paleti",
            "paletteSub" to "Uygulama Teması",
            "languageTitle" to "Dili Değiştir",
            "languageSub" to "Arayüz Dili",
            "newChat" to "Yeni Sohbet",
            "chatHistory" to "SOHBET GEÇMİŞİ",
            "searchChatPlaceholder" to "Sohbetlerde ara...",
            "noHistory" to "Geçmiş Yok",
            "deleteChat" to "Sohbeti Sil",
            "openMenu" to "Menüyü Aç",
            "aiLiveMode" to "Zann AI Canlı",
            "toggleTheme" to "Temayı Değiştir",
            "typeMessagePlaceholder" to "Zann AI'ya mesajınızı yazın...",
            "tutorPhotoTask" to "Yapay Zeka Ödev Fotoğraf Eğitmeni",
            "addFile" to "Dosya Ekle",
            "webGrounding" to "Web Araması",
            "webGroundingOn" to "Otomatik Web Araması Açık",
            "webGroundingOff" to "Çevrimdışı Yanıtlar",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "ÖNERİLEN İSTEMLER",
            "welcomeText" to "Dosya yükleme ve gerçek zamanlı sesli not desteği sunan akıllı yapay zeka asistanı.",
            "prompt1Title" to "Gelecek teknolojisi fikirleri",
            "prompt1Sub" to "İlham ve yaratıcı fikirler",
            "prompt2Title" to "İyi bir romanın kısa incelemesi",
            "prompt2Sub" to "Edebiyat önerisi",
            "prompt3Title" to "Verimli sabah rutini ipuçları",
            "prompt3Sub" to "Kişisel gelişim",
            "selectThemeTitle" to "Renk Teması Seçin",
            "selectThemeSub" to "Uygulama için bir renk teması seçin:",
            "selectLanguageTitle" to "Dili Değiştir",
            "selectLanguageSub" to "Uygulama arayüz dilini seçin:",
            "close" to "Kapat",
            "cancel" to "İptal",
            "save" to "Kaydet",
            "active" to "Aktif",
            "voiceRecord" to "Ses Kaydediliyor",
            "systemGrayTheme" to "Sistem (Koyu Gri)",
            "systemGrayDesc" to "Koyu Gri, Minimalist"
        ),
        "nl" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "Slimme AI Assistent",
            "onlineRealtime" to "Online & Realtime",
            "fitur" to "Functies",
            "flashcardTitle" to "Zann AI Flitskaarten",
            "flashcardSub" to "Quizzen & Auto-generator",
            "memoryTitle" to "Zann AI Leergeheugen",
            "memorySub" to "Aangepaste Kennisbank",
            "plannerTitle" to "Zann AI Studieplanner",
            "plannerSub" to "Onderwerpen Opbreken per Doel",
            "paletteTitle" to "Zann AI Kleurenpalet",
            "paletteSub" to "App Thema & Kleuren",
            "languageTitle" to "Taal Wijzigen",
            "languageSub" to "Weergavetaal Zann AI",
            "newChat" to "Nieuw Gesprek",
            "chatHistory" to "GESPREKSGESCHIEDENIS",
            "searchChatPlaceholder" to "Zoek gesprekken...",
            "noHistory" to "Nog Geen Geschiedenis",
            "deleteChat" to "Verwijder Chat",
            "openMenu" to "Open Menu",
            "aiLiveMode" to "Zann AI Live",
            "toggleTheme" to "Wissel Thema",
            "typeMessagePlaceholder" to "Typ je bericht aan Zann AI...",
            "tutorPhotoTask" to "AI Huiswerk Foto Tutor",
            "addFile" to "Bestand Toevoegen",
            "webGrounding" to "Web zoeken",
            "webGroundingOn" to "Automatisch Zoeken Aan",
            "webGroundingOff" to "Zonder Web zoeken",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "AANBEVOLEN PROMPTS",
            "welcomeText" to "Slimme online AI-assistent met bestandsuploads en realtime spraaknotities.",
            "prompt1Title" to "Ideeën voor toekomstige technologie",
            "prompt1Sub" to "Inspiratie & creativiteit",
            "prompt2Title" to "Korte recensie van een goed boek",
            "prompt2Sub" to "Literatuuraanbeveling",
            "prompt3Title" to "Tips voor een productieve ochtend",
            "prompt3Sub" to "Persoonlijke groei",
            "selectThemeTitle" to "Kies Kleurenthema",
            "selectThemeSub" to "Kies een kleurenschema voor Zann AI:",
            "selectLanguageTitle" to "Taal Wijzigen",
            "selectLanguageSub" to "Selecteer de weergavetaal voor de app:",
            "close" to "Sluiten",
            "cancel" to "Annuleren",
            "save" to "Opslaan",
            "active" to "Actief",
            "voiceRecord" to "Spraakopname",
            "systemGrayTheme" to "Systeem (Donkergrijs)",
            "systemGrayDesc" to "Donkergrijs, Minimalistisch"
        ),
        "pl" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "Inteligentny Asystent AI",
            "onlineRealtime" to "Online i w czasie rzeczywistym",
            "fitur" to "Funkcje",
            "flashcardTitle" to "Fiszki Zann AI",
            "flashcardSub" to "Quizy i Automatyczny Generator",
            "memoryTitle" to "Pamięć Nauki Zann AI",
            "memorySub" to "Własna Baza Wiedzy",
            "plannerTitle" to "Planer Nauki Zann AI",
            "plannerSub" to "Podział Tematów według Celu",
            "paletteTitle" to "Paleta Barw Zann AI",
            "paletteSub" to "Motyw i Kolory Aplikacji",
            "languageTitle" to "Zmień Język",
            "languageSub" to "Język Interfejsu Zann AI",
            "newChat" to "Nowa Rozmowa",
            "chatHistory" to "HISTORIA CZATU",
            "searchChatPlaceholder" to "Szukaj czatów...",
            "noHistory" to "Brak Historii",
            "deleteChat" to "Usuń Czat",
            "openMenu" to "Otwórz Menu",
            "aiLiveMode" to "Zann AI Na Żywo",
            "toggleTheme" to "Zmień Motyw",
            "typeMessagePlaceholder" to "Napisz wiadomość do Zann AI...",
            "tutorPhotoTask" to "Korepetytor Zdjęć Zadania AI",
            "addFile" to "Dołącz Plik",
            "webGrounding" to "Wyszukiwanie Web",
            "webGroundingOn" to "Automatyczne Szukanie Włączone",
            "webGroundingOff" to "Bez Szukania w Sieci",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "ZALECANE PODPOWIEDZI",
            "welcomeText" to "Inteligentny asystent AI online z obsługą plików i notatek głosowych w czasie rzeczywistym.",
            "prompt1Title" to "Pomysły na technologie przyszłości",
            "prompt1Sub" to "Inspiracja i pomysły",
            "prompt2Title" to "Krótka recenzja dobrej książki",
            "prompt2Sub" to "Rekomendacja literacka",
            "prompt3Title" to "Porady na produktywny poranek",
            "prompt3Sub" to "Rozwój osobisty",
            "selectThemeTitle" to "Wybierz Motyw Kolorów",
            "selectThemeSub" to "Wybierz schemat kolorów dla aplikacji:",
            "selectLanguageTitle" to "Zmień Język",
            "selectLanguageSub" to "Wybierz język interfejsu aplikacji:",
            "close" to "Zamknij",
            "cancel" to "Anuluj",
            "save" to "Zapisz",
            "active" to "Aktywny",
            "voiceRecord" to "Nagrywanie Notatki Głosowej",
            "systemGrayTheme" to "Systemowy (Ciemnoszary)",
            "systemGrayDesc" to "Ciemnoszary, Minimalistyczny"
        ),
        "hi" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "स्मार्ट एआई सहायक",
            "onlineRealtime" to "ऑनलाइन और रियल-टाइम",
            "fitur" to "विशेषताएं",
            "flashcardTitle" to "Zann AI फ्लैशकार्ड",
            "flashcardSub" to "क्विज़ और ऑटो जनरेटर",
            "memoryTitle" to "Zann AI लर्निंग मेमोरी",
            "memorySub" to "कस्टम ज्ञान आधार",
            "plannerTitle" to "Zann AI स्टडी प्लानर",
            "plannerSub" to "लक्ष्य के अनुसार विषय विभाजन",
            "paletteTitle" to "Zann AI कलर पैलेट",
            "paletteSub" to "ऐप थीम और रंग",
            "languageTitle" to "भाषा बदलें",
            "languageSub" to "Zann AI इंटरफ़ेस भाषा",
            "newChat" to "नई बातचीत",
            "chatHistory" to "चैट इतिहास",
            "searchChatPlaceholder" to "चैट खोजें...",
            "noHistory" to "कोई इतिहास नहीं",
            "deleteChat" to "चैट हटाएं",
            "openMenu" to "मेनू खोलें",
            "aiLiveMode" to "Zann AI लाइव",
            "toggleTheme" to "थीम बदलें",
            "typeMessagePlaceholder" to "Zann AI को अपना संदेश लिखें...",
            "tutorPhotoTask" to "एआई होमवर्क फोटो ट्यूटर",
            "addFile" to "फ़ाइल संलग्न करें",
            "webGrounding" to "वेब खोज",
            "webGroundingOn" to "ऑटो वेब खोज सक्रिय",
            "webGroundingOff" to "वेब खोज के बिना",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "अनुशंसित प्रॉम्प्ट",
            "welcomeText" to "फ़ाइल अपलोड और रियल-टाइम वॉयस नोट्स के साथ स्मार्ट ऑनलाइन एआई सहायक।",
            "prompt1Title" to "भविष्य की तकनीक के विचार",
            "prompt1Sub" to "प्रेरणा और रचनात्मक विचार",
            "prompt2Title" to "एक अच्छी किताब की संक्षिप्त समीक्षा",
            "prompt2Sub" to "साहित्य अनुशंसा",
            "prompt3Title" to "उत्पादक सुबह की दिनचर्या के टिप्स",
            "prompt3Sub" to "व्यक्तिगत विकास",
            "selectThemeTitle" to "रंग थीम चुनें",
            "selectThemeSub" to "ऐप के लिए एक आकर्षक रंग योजना चुनें:",
            "selectLanguageTitle" to "भाषा बदलें",
            "selectLanguageSub" to "संपूर्ण ऐप के लिए भाषा चुनें:",
            "close" to "बंद करें",
            "cancel" to "रद्द करें",
            "save" to "सहेजें",
            "active" to "सक्रिय",
            "voiceRecord" to "वॉयस नोट रिकॉर्डिंग",
            "systemGrayTheme" to "सिस्टम (गहरा धूसर)",
            "systemGrayDesc" to "गहरा धूसर, न्यूट्रल"
        ),
        "vi" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "Trợ Lý AI Thông Minh",
            "onlineRealtime" to "Trực Tuyến & Trực Tiếp",
            "fitur" to "Tính Năng",
            "flashcardTitle" to "Thẻ Ghi Nhớ Zann AI",
            "flashcardSub" to "Trắc Nghiệm & Tạo Tự Động",
            "memoryTitle" to "Bộ Nhớ Học Tập Zann AI",
            "memorySub" to "Cơ Sở Kiến Thức Tùy Chỉnh",
            "plannerTitle" to "Kế Hoạch Học Tập Zann AI",
            "plannerSub" to "Phân Tích Chủ Đề Theo Mục Tiêu",
            "paletteTitle" to "Bảng Màu Zann AI",
            "paletteSub" to "Chủ Đề & Phối Màu App",
            "languageTitle" to "Đổi Ngôn Ngữ",
            "languageSub" to "Ngôn Ngữ Hiển Thị Zann AI",
            "newChat" to "Cuộc Trò Chuyện Mới",
            "chatHistory" to "LỊCH SỬ TRÒ CHUYỆN",
            "searchChatPlaceholder" to "Tìm kiếm cuộc trò chuyện...",
            "noHistory" to "Chưa Có Lịch Sử",
            "deleteChat" to "Xóa Trò Chuyện",
            "openMenu" to "Mở Menu",
            "aiLiveMode" to "Zann AI Trực Tiếp",
            "toggleTheme" to "Đổi Giao Diện",
            "typeMessagePlaceholder" to "Nhập tin nhắn cho Zann AI...",
            "tutorPhotoTask" to "Gia Sư AI Giải Bằng Ảnh",
            "addFile" to "Thêm Tệp Tin",
            "webGrounding" to "Tìm Kiếm Web",
            "webGroundingOn" to "Tự Động Tìm Kiếm Web",
            "webGroundingOff" to "Không Tìm Kiếm Web",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "GỢI Ý HỎI ĐÁP",
            "welcomeText" to "Trợ lý AI thông minh trực tuyến hỗ trợ gửi tệp và ghi âm giọng nói thời gian thực.",
            "prompt1Title" to "Ý tưởng công nghệ tương lai",
            "prompt1Sub" to "Cảm hứng & ý tưởng sáng tạo",
            "prompt2Title" to "Tóm tắt sách tiểu thuyết hay",
            "prompt2Sub" to "Gợi ý văn học",
            "prompt3Title" to "Mẹo thói quen buổi sáng hiệu quả",
            "prompt3Sub" to "Phát triển bản thân",
            "selectThemeTitle" to "Chọn Chủ Đề Màu",
            "selectThemeSub" to "Chọn phối màu cho giao diện ứng dụng:",
            "selectLanguageTitle" to "Đổi Ngôn Ngữ Zann AI",
            "selectLanguageSub" to "Chọn ngôn ngữ hiển thị cho toàn bộ ứng dụng:",
            "close" to "Đóng",
            "cancel" to "Hủy",
            "save" to "Lưu",
            "active" to "Đang dùng",
            "voiceRecord" to "Ghi Âm Giọng Nói",
            "systemGrayTheme" to "Hệ Thống (Xám Đậm)",
            "systemGrayDesc" to "Xám Đậm, Tối Giản"
        ),
        "th" to mapOf(
            "appName" to "Zann AI",
            "appSubtitle" to "ผู้ช่วย AI อัจฉริยะ",
            "onlineRealtime" to "ออนไลน์ & เรียลไทม์",
            "fitur" to "ฟีเจอร์",
            "flashcardTitle" to "แฟลชการ์ด Zann AI",
            "flashcardSub" to "ควิซ & สร้างอัตโนมัติ",
            "memoryTitle" to "ความจำการเรียนรู้ Zann AI",
            "memorySub" to "คลังความรู้ส่วนตัว",
            "plannerTitle" to "แผนการเรียน Zann AI",
            "plannerSub" to "ย่อยหัวข้อตามเป้าหมาย",
            "paletteTitle" to "จานสี Zann AI",
            "paletteSub" to "ธีมและโทนสีแอป",
            "languageTitle" to "เปลี่ยนภาษา",
            "languageSub" to "ภาษาการแสดงผล Zann AI",
            "newChat" to "แชทใหม่",
            "chatHistory" to "ประวัติการแชท",
            "searchChatPlaceholder" to "ค้นหาแชท...",
            "noHistory" to "ยังไม่มีประวัติ",
            "deleteChat" to "ลบแชท",
            "openMenu" to "เปิดเมนู",
            "aiLiveMode" to "Zann AI ไลฟ์",
            "toggleTheme" to "เปลี่ยนธีม",
            "typeMessagePlaceholder" to "พิมพ์ข้อความถึง Zann AI...",
            "tutorPhotoTask" to "ติวเตอร์ AI จากภาพถ่ายการบ้าน",
            "addFile" to "แนบไฟล์",
            "webGrounding" to "ค้นหาเว็บ",
            "webGroundingOn" to "เปิดค้นหาเว็บอัตโนมัติ",
            "webGroundingOff" to "ปิดการค้นหาเว็บ",
            "modelPro" to "Zann Pro",
            "modelFlash" to "Zann Flash",
            "recommendedPrompts" to "พรอมต์แนะนำ",
            "welcomeText" to "ผู้ช่วย AI ออนไลน์อัจฉริยะที่รองรับการอัปโหลดไฟล์และบันทึกเสียงแบบเรียลไทม์",
            "prompt1Title" to "ไอเดียเทคโนโลยีแห่งอนาคต",
            "prompt1Sub" to "แรงบันดาลใจและไอเดียสร้างสรรค์",
            "prompt2Title" to "รีวิวนิยายดีๆ แบบสั้น",
            "prompt2Sub" to "แนะนำวรรณกรรม",
            "prompt3Title" to "เคล็ดลับยามเช้าให้มีประสิทธิภาพ",
            "prompt3Sub" to "การพัฒนาตนเอง",
            "selectThemeTitle" to "เลือกธีมสี",
            "selectThemeSub" to "เลือกโทนสีที่ต้องการสำหรับแอป:",
            "selectLanguageTitle" to "เปลี่ยนภาษา Zann AI",
            "selectLanguageSub" to "เลือกภาษาที่ต้องการใช้ในแอป:",
            "close" to "ปิด",
            "cancel" to "ยกเลิก",
            "save" to "บันทึก",
            "active" to "ใช้งานอยู่",
            "voiceRecord" to "กำลังบันทึกเสียง",
            "systemGrayTheme" to "ระบบ (เทาเข้ม)",
            "systemGrayDesc" to "เทาเข้ม มินิมอล"
        )
    )

    fun getString(key: String, langCode: String): String {
        val langMap = translations[langCode] ?: translations["en"] ?: translations["id"]!!
        return langMap[key] ?: translations["id"]?.get(key) ?: key
    }
}
